name: Bug Report
description: Report software or implementation error.
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Please search the [issue tracker](https://github.com/HenryRWinterbottom/nwp_stacks/issues) before issuing a bug report.

  - type: textarea
    id: current_behavior
    attributes:
      label: What is wrong?
      description: Give a brief description of what is incorrect or broken.
      placeholder: |
        Short log snippets that illustrate the problem can be included here.

        For any longer logs, please create a GitHub gist (https://gist.github.com/) and link it here.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: The expected behavior.
      placeholder: Describe what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: The type of OS or platform.
      description: You may select multiple machines.
      multiple: true
      options:
        - OSX/Darwin
        - Linux
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Reproduction Steps
      description: Please give explicit instructions to reproduce the error
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Additional Information
      description: Provide context or any additional information about the bug.
    validations:
      required: true

  - type: textarea
    id: proposed_implementation
    attributes:
      label: Do you have a proposed solution?
      description: If you already have an idea on how to fix this, please provide it here.
      placeholder: Optional
    validations:
      required: false
